
// File: database/places-data.js
// النسخة النهائية الكاملة - مع الحل الهجين للصور (Hybrid Image Solution)
// تم إضافة صور يدوية دقيقة للأماكن الشهيرة، والبقية ستُجلب تلقائيًا.

export const initialPlaces = [
    // --- معالم سياحية (1-20) ---
    {
        id: 1,
        name: 'أبراج الكويت',
        category: 'معلم سياحي',
        description: 'أحد أبرز معالم الكويت الحديثة، وتوفر إطلالة بانورامية على المدينة والخليج.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuwait+Towers',
        imageUrl: 'https://www.arabianbusiness.com/cloud/2021/09/14/j2Lz75Vf-kuwait-towers-1200x800.jpg',
        tags: ['إطلالة', 'بانوراما', 'تاريخ', 'تصوير', 'معلم'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 2,
        name: 'مركز الشيخ جابر الأحمد الثقافي',
        category: 'معلم سياحي',
        description: 'صرح معماري فريد يستضيف فعاليات ثقافية وفنية ومسرحيات عالمية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sheikh+Jaber+Al-Ahmad+Cultural+Centre',
        imageUrl: 'https://www.jacc-kw.com/Files/Events/jacc-pc-02-original.jpg',
        tags: ['ثقافة', 'فن', 'مسرح', 'عروض', 'دار الأوبرا'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 3,
        name: 'مركز الشيخ عبدالله السالم الثقافي',
        category: 'معلم سياحي',
        description: 'رحلة ممتعة عبر متاحف العلوم والتاريخ الطبيعي والفضاء.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sheikh+Abdullah+Al+Salem+Cultural+Centre',
        imageUrl: 'https://ascckw.com/wp-content/uploads/2022/04/ascc-1.jpg',
        tags: ['متحف', 'علوم', 'تاريخ', 'فضاء', 'عائلي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 4,
        name: 'حديقة الشهيد',
        category: 'معلم سياحي',
        description: 'واحة خضراء في قلب المدينة مثالية للمشي والفعاليات الثقافية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Al+Shaheed+Park+Kuwait',
        imageUrl: 'https://www.alshaheedpark.com/media/1020/home-banner-2.jpg',
        tags: ['حديقة', 'طبيعة', 'مشي', 'هدوء', 'متحف'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 5,
        name: 'المسجد الكبير',
        category: 'معلم سياحي',
        description: 'صرح إسلامي بتصميم أندلسي مذهل تجربة روحانية وهندسة معمارية فريدة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Grand+Mosque+of+Kuwait',
        imageUrl: 'https://media.tacdn.com/media/attractions-splice-spp-674x446/07/26/a3/35.jpg',
        tags: ['ديني', 'إسلامي', 'معماري', 'هدوء', 'روحاني'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 6,
        name: 'سوق المباركية',
        category: 'معلم سياحي',
        description: 'قلب الكويت النابض، يجمع بين التراث والتسوق والمطاعم الشعبية.',
        locationName: 'القبلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Souk+Al-Mubarakiya+Kuwait',
        imageUrl: 'https://www.justfared.com/wp-content/uploads/2020/01/souk-mubarakiya-kuwait.jpg',
        tags: ['تراث', 'شعبي', 'سوق', 'تاريخ', 'مطاعم'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 7,
        name: 'متحف الكويت الوطني',
        category: 'معلم سياحي',
        description: 'استكشف تاريخ الكويت وتراثها الغني في مكان واحد.',
        locationName: 'القبلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuwait+National+Museum',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Kuwait_National_Museum_2020.jpg',
        tags: ['متحف', 'تاريخ', 'تراث', 'آثار'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 8,
        name: 'بيت المرايا',
        category: 'معلم سياحي',
        description: 'منزل فني فريد مغطى بالكامل بفسيفساء المرايا، تجربة بصرية لا تُنسى.',
        locationName: 'القادسية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=House+of+Mirrors+Kuwait',
        imageUrl: 'https://i0.wp.com/artandseek.org/wp-content/uploads/2016/10/Mirror-House_4.jpg',
        tags: ['فن', 'فريد', 'فسيفساء', 'بصري'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 9,
        name: 'بيت العثمان',
        category: 'معلم سياحي',
        description: 'متحف يروي قصة الكويت القديمة بأسلوب شيق.',
        locationName: 'حولي',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bait+Al-Othman+Museum+Kuwait',
        imageUrl: 'https://live.staticflickr.com/5650/23011488663_e2c262a033_b.jpg',
        tags: ['متحف', 'تاريخ', 'قديم', 'تراث'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 10,
        name: 'المركز العلمي',
        category: 'معلم سياحي',
        description: 'يضم أكواريوم وسينما آيماكس، تجربة ممتعة للعائلة.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Scientific+Center+Kuwait',
        imageUrl: 'https://tsck.org.kw/wp-content/uploads/2021/08/TSCK-Building.jpg',
        tags: ['أكواريوم', 'سينما', 'عائلي', 'أطفال', 'ترفيه'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 11,
        name: 'برج التحرير',
        category: 'معلم سياحي',
        description: 'أحد أطول أبراج الاتصالات في العالم، معلم بارز في سماء الكويت.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Liberation+Tower+Kuwait',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Liberation_Tower_-_Kuwait.jpg',
        tags: ['برج', 'معلم', 'هندسة معمارية', 'اتصالات'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 12,
        name: 'جزيرة فيلكا',
        category: 'معلم سياحي',
        description: 'رحلة بالعبّارة إلى جزيرة تاريخية تجمع بين الآثار والهدوء.',
        locationName: 'جزيرة فيلكا',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Failaka+Island+Kuwait',
        imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/2f/18/d8/failaka-island.jpg?w=1200&h=-1&s=1',
        tags: ['جزيرة', 'تاريخ', 'آثار', 'هدوء', 'بحر'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 13,
        name: 'قصر السيف',
        category: 'معلم سياحي',
        description: 'معلم تاريخي يتميز ببرجه المغطى بالسيراميك الأزرق يطل على الخليج.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Seif+Palace+Kuwait',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Seif_Palace_in_Kuwait_City.jpg',
        tags: ['قصر', 'تاريخ', 'معماري', 'تراث'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 14,
        name: 'بيت السدو',
        category: 'معلم سياحي',
        description: 'مكان للحفاظ على فن النسيج التقليدي، يعرض قطعًا فنية رائعة.',
        locationName: 'بجانب المتحف الوطني',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sadu+House+Kuwait',
        imageUrl: 'https://www.visit-kuwait.com/wp-content/uploads/2019/12/sadu-house.jpg',
        tags: ['تراث', 'نسيج', 'فن', 'تقليدي', 'حرف يدوية'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 15,
        name: 'متحف طارق رجب للخط الإسلامي',
        category: 'معلم سياحي',
        description: 'مجموعة خاصة ونادرة من المخطوطات والقطع الفنية الإسلامية.',
        locationName: 'الجابرية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tareq+Rajab+Museum+of+Islamic+Calligraphy',
        imageUrl: '',
        tags: ['متحف', 'إسلامي', 'خط', 'فن', 'تاريخ'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 16,
        name: 'المارينا كريست',
        category: 'معلم سياحي',
        description: 'واجهة بحرية بتصميم مميز تضم مطاعم ومقاهي بإطلالات خلابة.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Marina+Crescent+Kuwait',
        imageUrl: 'https://live.staticflickr.com/5092/5482381284_9c56580f55_b.jpg',
        tags: ['بحر', 'إطلالة', 'مطاعم', 'مقاهي', 'ممشى'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 17,
        name: 'يوم البحار',
        category: 'معلم سياحي',
        description: 'قرية تراثية تحاكي حياة أهل الكويت في الماضي.',
        locationName: 'بجانب مجلس الأمة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Yaum+Al-Bahhar+Village+Kuwait',
        imageUrl: 'https://www.hello-kuwait.com/wp-content/uploads/2021/09/Yacht-Club-Kuwait-1024x680-1.jpg',
        tags: ['تراث', 'قرية', 'تاريخ', 'بحر'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 18,
        name: 'متحف السيارات التاريخية والقديمة',
        category: 'معلم سياحي',
        description: 'لعشاق السيارات الكلاسيكية، رحلة عبر تاريخ المحركات.',
        locationName: 'الشويخ الصناعية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Historical,+Vintage+and+Classic+Car+Museum+Kuwait',
        imageUrl: 'https://www.automuseum.com.kw/Content/images/about-museum.jpg',
        tags: ['سيارات', 'كلاسيك', 'متحف', 'تاريخ', 'محركات'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 19,
        name: 'نصب الشهداء (قرين)',
        category: 'معلم سياحي',
        description: 'نصب تذكاري يخلّد ذكرى المقاومة الكويتية.',
        locationName: 'القرين',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Al-Qurain+Martyrs+Museum+Kuwait',
        imageUrl: '',
        tags: ['تاريخ', 'نصب تذكاري', 'وطني'],
        suitableFor: ['individual', 'group'],
    },
    {
        id: 20,
        name: 'شاطئ الشويخ',
        category: 'معلم سياحي',
        description: 'مكان هادئ للمشي والاستمتاع بمنظر البحر وأبراج الكويت.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Shuwaikh+Beach+Kuwait',
        imageUrl: '',
        tags: ['شاطئ', 'بحر', 'مشي', 'هدوء', 'منظر'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    // --- مجمعات تجارية (21-34) ---
    {
        id: 21,
        name: 'الأفنيوز',
        category: 'مجمع تجاري',
        description: 'أكبر مجمع تجاري في الكويت، تجربة تسوق وترفيه متكاملة لا مثيل لها.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Avenues+Mall+Kuwait',
        imageUrl: 'https://www.the-avenues.com/kuwait/wp-content/uploads/2021/08/grand-avenue-2.jpg',
        tags: ['تسوق', 'ماركات', 'سينما', 'ترفيه', 'مطاعم'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 22,
        name: 'مول 360',
        category: 'مجمع تجاري',
        description: 'تصميم فاخر وماركات عالمية وسينما VIP لتجربة تسوق راقية.',
        locationName: 'جنوب السرة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=360+Mall+Kuwait',
        imageUrl: 'https://www.360-kuwait.com/sites/default/files/2021-12/1200x630.jpg',
        tags: ['تسوق', 'فاخر', 'ماركات', 'سينما', 'راقي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 23,
        name: 'مارينا مول',
        category: 'مجمع تجاري',
        description: 'يجمع بين التسوق والواجهة البحرية، مثالي ليوم كامل من الأنشطة.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Marina+Mall+Salmiya+Kuwait',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Marina_Mall_in_Kuwait.jpg',
        tags: ['بحر', 'تسوق', 'مطاعم', 'أنشطة', 'عائلي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 24,
        name: 'مول الكوت',
        category: 'مجمع تجاري',
        description: 'وجهة عائلية متكاملة مع نافورة راقصة وسوق تقليدي وإطلالة بحرية.',
        locationName: 'الفحيحيل',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Al+Kout+Mall+Kuwait',
        imageUrl: 'https://alkout.com.kw/App_Themes/Super-Cms/images/home_banner.jpg',
        tags: ['عائلي', 'نافورة', 'بحر', 'تسوق', 'سوق شعبي'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 25,
        name: 'مجمع الصالحية التجاري',
        category: 'مجمع تجاري',
        description: 'وجهة الماركات الفاخرة والراقية في قلب العاصمة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Salhia+Complex+Kuwait',
        imageUrl: '',
        tags: ['تسوق', 'فاخر', 'ماركات', 'راقي', 'بوتيكات'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 26,
        name: 'ذا جيت مول',
        category: 'مجمع تجاري',
        description: 'تصميم عصري ومزيج جيد من المحلات والمطاعم في منطقة حيوية.',
        locationName: 'العقيلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Gate+Mall+Egaila+Kuwait',
        imageUrl: 'https://thegatemall.com.kw/wp-content/uploads/2020/09/the-gate-mall.jpg',
        tags: ['تسوق', 'عصري', 'مطاعم', 'مقاهي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 27,
        name: 'مجمع الحمراء',
        category: 'مجمع تجاري',
        description: 'يضم أطول ناطحة سحاب في الكويت، ويوفر تجربة تسوق فاخر ومطاعم بإطلالات بانورامية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Al+Hamra+Luxury+Center+Kuwait',
        imageUrl: 'https://www.alhamra.com.kw/images/At-Al-Hamra-Shopping-Center-and-Offices-in-Kuwait-City-1.jpg',
        tags: ['فاخر', 'إطلالة', 'تسوق', 'ناطحة سحاب', 'راقي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 28,
        name: 'مروج',
        category: 'مجمع تجاري',
        description: 'مجمع مفتوح يجمع بين المطاعم الراقية والمساحات الخضراء، مثالي للمساء.',
        locationName: 'صباح السالم',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Murouj+Kuwait',
        imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipP_Lh2m2A6g1p2B9iQ0J2aJg0xZ8s6C_vXzHw=s1360-w1360-h1020',
        tags: ['مفتوح', 'مطاعم', 'مساحات خضراء', 'مساء', 'راقي'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 29,
        name: 'سوق شرق',
        category: 'مجمع تجاري',
        description: 'تصميم يجمع بين السوق التقليدي والمجمع الحديث على الواجهة البحرية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Souq+Sharq+Kuwait',
        imageUrl: '',
        tags: ['بحر', 'سوق', 'تقليدي', 'مطاعم', 'تسوق'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 30,
        name: 'بوليفارد',
        category: 'مجمع تجاري',
        description: 'مساحات خضراء واسعة وبحيرة صناعية ومطاعم متنوعة، مثالي للعائلات.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Boulevard+Mall+Salmiya',
        imageUrl: '',
        tags: ['عائلي', 'مساحات خضراء', 'بحيرة', 'مطاعم'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 31,
        name: 'مجمع أرجان البدع',
        category: 'مجمع تجاري',
        description: 'يضم مجموعة من أفضل المطاعم والمقاهي في أجواء مفتوحة ومريحة.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Argan+Al-Bidaa+Kuwait',
        imageUrl: '',
        tags: ['مفتوح', 'مطاعم', 'مقاهي', 'مريح'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 32,
        name: 'ذا ووك',
        category: 'مجمع تجاري',
        description: 'مجمع مفتوح بطابع عصري في منطقة العقيلة، خيار ممتاز للمطاعم والترفيه.',
        locationName: 'العقيلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Walk+Mall+Egaila',
        imageUrl: '',
        tags: ['مفتوح', 'عصري', 'مطاعم', 'ترفيه'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 33,
        name: 'ذا ليك (أبو الحصانية)',
        category: 'مجمع تجاري',
        description: 'مجمع مطاعم راقٍ حول بحيرة، مثالي لعشاء هادئ ومميز.',
        locationName: 'أبو الحصانية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Lake+Complex+Abu+Al+Hasaniya',
        imageUrl: '',
        tags: ['بحيرة', 'راقي', 'مطاعم', 'عشاء', 'هدوء'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 34,
        name: 'ليوان مول',
        category: 'مجمع تجاري',
        description: 'مجمع جديد في العقيلة يقدم تجربة تسوق ومطاعم متنوعة.',
        locationName: 'العقيلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Liwan+Mall+Egaila',
        imageUrl: '',
        tags: ['جديد', 'تسوق', 'مطاعم'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    // --- ترفيه ونشاط (35-60) ---
    {
        id: 35,
        name: 'العاصمة مول',
        category: 'ترفيه ونشاط',
        description: 'مجمع جديد في العاصمة بتصميم مذهل ومحلات حصرية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Assima+Mall+Kuwait',
        imageUrl: 'https://theassimamall.com/wp-content/uploads/2023/10/About-Page-scaled.jpg',
        tags: ['جديد', 'تسوق', 'حصري', 'فاخر'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 36,
        name: 'إنفنتي (مول 360)',
        category: 'ترفيه ونشاط',
        description: 'مركز ترفيهي عائلي ضخم بتقنيات حديثة وألعاب متنوعة.',
        locationName: 'جنوب السرة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Infunity+360+Mall+Kuwait',
        imageUrl: '',
        tags: ['ترفيه', 'عائلي', 'ألعاب', 'أطفال'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 37,
        name: 'ترامبواكستريم (مروج)',
        category: 'ترفيه ونشاط',
        description: 'مكان مثالي لتفريغ الطاقة مع ألعاب القفز والتسلق.',
        locationName: 'صباح السالم',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Trampo+Extreme+Murouj+Kuwait',
        imageUrl: '',
        tags: ['قفز', 'تسلق', 'ترامبولين', 'حركة', 'شباب'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 38,
        name: 'كويت كارتينج',
        category: 'ترفيه ونشاط',
        description: 'اختبر مهاراتك في القيادة في حلبة سباق سيارات ممتعة.',
        locationName: 'الأحمدي',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuwait+Karting+Ahmadi',
        imageUrl: '',
        tags: ['سباق', 'سيارات', 'كارتينج', 'سرعة', 'مغامرة'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 39,
        name: 'حلبة مدينة الكويت للمحركات',
        category: 'ترفيه ونشاط',
        description: 'لعشاق السرعة، استمتع بسباقات احترافية وتجارب قيادة مثيرة.',
        locationName: 'عريفجان',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuwait+Motor+Town',
        imageUrl: '',
        tags: ['سرعة', 'سباق', 'محركات', 'احترافي', 'قيادة'],
        suitableFor: ['individual', 'group'],
    },
    {
        id: 40,
        name: 'منتزه الخيران',
        category: 'ترفيه ونشاط',
        description: 'شاليهات وأنشطة بحرية متنوعة لقضاء عطلة نهاية أسبوع ممتعة.',
        locationName: 'الخيران',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Khiran+Resort+Kuwait',
        imageUrl: '',
        tags: ['شاليه', 'بحر', 'عطلة', 'أنشطة مائية', 'عائلي'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 41,
        name: 'حديقة حيوان الكويت',
        category: 'ترفيه ونشاط',
        description: 'تعرف على أنواع مختلفة من الحيوانات في نزهة عائلية كلاسيكية.',
        locationName: 'العمرية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuwait+Zoo',
        imageUrl: '',
        tags: ['حيوانات', 'حديقة', 'عائلي', 'أطفال', 'نزهة'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 42,
        name: 'ماجيك بلانيت (الأفنيوز)',
        category: 'ترفيه ونشاط',
        description: 'مدينة ألعاب داخلية ضخمة تناسب جميع الأعمار.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Magic+Planet+The+Avenues+Kuwait',
        imageUrl: '',
        tags: ['ألعاب', 'ترفيه', 'أطفال', 'عائلي'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 43,
        name: 'كيدزانيا (الأفنيوز)',
        category: 'ترفيه ونشاط',
        description: 'مدينة تعليمية ترفيهية للأطفال ليعيشوا تجربة المهن المختلفة.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=KidZania+The+Avenues+Kuwait',
        imageUrl: 'https://kuwait.kidzania.com/sites/default/files/styles/12_8_r_840x560/public/2019-10/KZKW%20WEBSITE%20-%20About%20KZKW.jpg',
        tags: ['أطفال', 'تعليمي', 'ترفيهي', 'مهن', 'عائلي'],
        suitableFor: ['family'],
    },
    {
        id: 44,
        name: 'أكوا بارك',
        category: 'ترفيه ونشاط',
        description: 'أكبر حديقة ألعاب مائية في الكويت، مثالية للهروب من حرارة الصيف.',
        locationName: 'بجانب أبراج الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Aqua+Park+Kuwait',
        imageUrl: '',
        tags: ['ألعاب مائية', 'صيف', 'عائلي', 'أطفال', 'مرح'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 45,
        name: 'نادي الرماية الكويتي',
        category: 'ترفيه ونشاط',
        description: 'تجربة فريدة لهواة الرماية في بيئة آمنة واحترافية.',
        locationName: 'السادس',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuwait+Shooting+Club',
        imageUrl: '',
        tags: ['رماية', 'هواية', 'تركيز', 'احترافي'],
        suitableFor: ['individual', 'group'],
    },
    {
        id: 46,
        name: 'نادي الفروسية',
        category: 'ترفيه ونشاط',
        description: 'لمشاهدة سباقات الخيل أو تعلم ركوب الخيل.',
        locationName: 'الصيد والفروسية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hunting+and+Equestrian+Club+Kuwait',
        imageUrl: '',
        tags: ['خيل', 'فروسية', 'سباق', 'رياضة'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 47,
        name: 'جزيرة كبر (رحلات)',
        category: 'ترفيه ونشاط',
        description: 'وجهة مثالية للغوص والسباحة في مياه صافية (عبر رحلات القوارب).',
        locationName: 'جنوب الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kubbar+Island+Kuwait',
        imageUrl: '',
        tags: ['بحر', 'غوص', 'سباحة', 'رحلة بحرية', 'جزيرة'],
        suitableFor: ['group'],
    },
    {
        id: 48,
        name: 'Paintball Kuwait',
        category: 'ترفيه ونشاط',
        description: 'أجمع أصدقاءك لمعركة ألوان حماسية ومليئة بالمغامرة.',
        locationName: 'السادس',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Paintball+Kuwait',
        imageUrl: '',
        tags: ['مغامرة', 'أصدقاء', 'مجموعة', 'لعبة', 'حماس'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 49,
        name: 'Pro Kart (ذا ووك)',
        category: 'ترفيه ونشاط',
        description: 'حلبة كارتينج خارجية ممتعة ومناسبة للشباب والعائلات.',
        locationName: 'العقيلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pro+Kart+The+Walk+Egaila',
        imageUrl: '',
        tags: ['كارتينج', 'سباق', 'شباب', 'عائلات', 'سرعة'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 50,
        name: 'Trapped Inn Escape Rooms',
        category: 'ترفيه ونشاط',
        description: 'هل يمكنك حل الألغاز والهروب من الغرفة في 60 دقيقة؟',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Trapped+Inn+Escape+Rooms+Salmiya',
        imageUrl: '',
        tags: ['ألغاز', 'هروب', 'فريق', 'ذكاء', 'تحدي'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 51,
        name: 'سينسكيب 360 (Imax & VIP)',
        category: 'ترفيه ونشاط',
        description: 'تجربة سينمائية فائقة الجودة.',
        locationName: 'جنوب السرة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cinescape+360+Mall',
        imageUrl: '',
        tags: ['سينما', 'VIP', 'Imax', 'أفلام', 'فاخر'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 52,
        name: 'سينسكيب الأفنيوز (Dolby Cinema)',
        category: 'ترفيه ونشاط',
        description: 'أحدث تقنيات الصوت والصورة لتجربة مشاهدة غامرة.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cinescape+The+Avenues',
        imageUrl: 'https://www.cinescape.com.kw/Cinescape/media/Pictures/Theatres/avenues-web-2.jpg',
        tags: ['سينما', 'Dolby', 'صوت', 'أفلام', 'تقنية'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 53,
        name: 'فوكس سينما (الكوت مول)',
        category: 'ترفيه ونشاط',
        description: 'خيارات متنوعة تشمل سينما الأطفال والـ VIP.',
        locationName: 'الفحيحيل',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=VOX+Cinemas+Al+Kout+Mall',
        imageUrl: '',
        tags: ['سينما', 'أطفال', 'VIP', 'أفلام', 'عائلي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 54,
        name: 'جراند سينما (الحمراء)',
        category: 'ترفيه ونشاط',
        description: 'سينما فاخرة بإطلالة مميزة في قلب العاصمة.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Grand+Cinemas+Al+Hamra+Tower',
        imageUrl: 'https://www.grandcinemas.com/images/locations/1366_640/grand_hamra_4.jpg',
        tags: ['سينما', 'فاخر', 'إطلالة', 'أفلام', 'راقي'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 55,
        name: 'شاطئ المسيلة',
        category: 'ترفيه ونشاط',
        description: 'شاطئ خاص نظيف ومناسب للعائلات مع العديد من الخدمات.',
        locationName: 'المسيلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Messilah+Beach+Kuwait',
        imageUrl: '',
        tags: ['شاطئ', 'بحر', 'عائلات', 'سباحة', 'استرخاء'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 56,
        name: 'شاطئ العقيلة',
        category: 'ترفيه ونشاط',
        description: 'شاطئ عام وممشى حيوي، مثالي للمشي والرياضة مساءً.',
        locationName: 'العقيلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Egaila+Beach+Park',
        imageUrl: '',
        tags: ['شاطئ', 'بحر', 'مشي', 'رياضة', 'مساء'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 57,
        name: "The Scientific Center's Dhow Harbor",
        category: 'ترفيه ونشاط',
        description: 'استمتع بمشاهدة سفن البوم التقليدية على الواجهة البحرية.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Scientific+Center+Kuwait+Dhow+Harbor',
        imageUrl: '',
        tags: ['بحر', 'سفن', 'تراث', 'تقليدي', 'منظر'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 58,
        name: 'Bounce Kuwait',
        category: 'ترفيه ونشاط',
        description: 'صالة ترامبولين ضخمة تقدم أنشطة متنوعة وممتعة.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=BOUNCE+Kuwait+Al+Rai',
        imageUrl: '',
        tags: ['ترامبولين', 'قفز', 'لياقة', 'مرح', 'عائلي'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 59,
        name: 'Ascend Rock Climbing',
        category: 'ترفيه ونشاط',
        description: 'جرب رياضة تسلق الصخور في صالة داخلية مجهزة بالكامل.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ascend+Kuwait+Climbing+Gym',
        imageUrl: '',
        tags: ['تسلق', 'رياضة', 'تحدي', 'مغامرة', 'لياقة'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 60,
        name: 'Clay Target Shooting',
        category: 'ترفيه ونشاط',
        description: 'تجربة رماية الأطباق الطائرة في الهواء الطلق.',
        locationName: 'الجهراء',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kuwait+Clay+Target+Shooting+Range',
        imageUrl: '',
        tags: ['رماية', 'هواء طلق', 'تركيز', 'تحدي'],
        suitableFor: ['individual', 'group'],
    },
    // --- مقاهي متخصصة (61-110) ---
    {
        id: 61,
        name: '% Arabica',
        category: 'مقهى متخصص',
        description: 'قهوة يابانية عالية الجودة في تصميم بسيط ومذهل.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=%+Arabica+Kuwait',
        imageUrl: 'https://images.squarespace-cdn.com/content/v1/5895744429687f48041773e3/1614051052157-550J68EVX20K49V4T1W2/art-culture-001-hero-2-desktop.jpg',
        tags: ['قهوة', 'مختصة', 'ياباني', 'تصميم', 'جودة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 62,
        name: 'Vol.1',
        category: 'مقهى متخصص',
        description: 'من رواد القهوة المختصة في الكويت، أجواء صناعية ومجتمع محب للقهوة.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vol.1+Cafe+Kuwait',
        imageUrl: 'https://b.zmtcdn.com/data/pictures/chains/4/18418084/b427b2c011e0388d447d3c01c713b185.jpg',
        tags: ['قهوة', 'مختصة', 'صناعي', 'مجتمع', 'رواد'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 63,
        name: "Toby's Estate",
        category: 'مقهى متخصص',
        description: 'علامة أسترالية شهيرة، مكان مثالي لتناول القهوة مع الفطور.',
        locationName: 'صباح السالم',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Toby\'s+Estate+Murouj+Kuwait',
        imageUrl: '',
        tags: ['قهوة', 'فطور', 'أسترالي', 'مشهور'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 64,
        name: 'Jumo Coffee Roasters',
        category: 'مقهى متخصص',
        description: 'محمصة محلية تقدم أنواع قهوة فريدة وأجواء هادئة للعمل.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Jumo+Coffee+Roasters+Shuwaikh',
        imageUrl: '',
        tags: ['قهوة', 'محمصة', 'هدوء', 'عمل', 'محلي'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 65,
        name: 'CAF',
        category: 'مقهى متخصص',
        description: 'مقهى ومحمصة يتميز بجودة القهوة وديكوره العصري.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=CAF+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['قهوة', 'عصري', 'محمصة', 'جودة', 'ديكور'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 66,
        name: "Richard's Coffee",
        category: 'مقهى متخصص',
        description: 'ديكور مستوحى من سباقات السيارات، مكان فريد ومختلف.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Richard\'s+Coffee+Bar+Shuwaikh',
        imageUrl: '',
        tags: ['قهوة', 'سيارات', 'ديكور', 'فريد'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 67,
        name: 'Magnet',
        category: 'مقهى متخصص',
        description: 'مساحة عمل ومقهى، مثالي للطلاب وأصحاب الأعمال الحرة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Magnet+Coworking+Space+Kuwait+City',
        imageUrl: '',
        tags: ['عمل', 'دراسة', 'طلاب', 'هدوء', 'مساحة عمل'],
        suitableFor: ['individual'],
    },
    {
        id: 68,
        name: 'Boost Cafe',
        category: 'مقهى متخصص',
        description: 'يركز على المشروبات الصحية والقهوة، أجواء مريحة وهادئة.',
        locationName: 'بنيد القار',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Boost+Cafe+Bneid+Al+Qar',
        imageUrl: '',
        tags: ['صحي', 'هدوء', 'مريح', 'قهوة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 69,
        name: 'Pause Coffee',
        category: 'مقهى متخصص',
        description: 'مكان صغير ومميز يقدم قهوة لذيذة وحلويات مبتكرة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pause+Coffee+Shuwaikh',
        imageUrl: '',
        tags: ['قهوة', 'حلويات', 'صغير', 'مبتكر'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 70,
        name: 'Grace',
        category: 'مقهى متخصص',
        description: 'مقهى بديكور أنيق وجميل، مناسب لجلسة قهوة بعد التسوق.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Grace+Cafe+The+Avenues',
        imageUrl: '',
        tags: ['ديكور', 'أنيق', 'تسوق', 'جميل'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 71,
        name: 'T La Felice',
        category: 'مقهى متخصص',
        description: 'مقهى إيطالي فاخر بتصميم كلاسيكي رائع.',
        locationName: 'العاصمة مول',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=T+La+Felice+Assima+Mall',
        imageUrl: '',
        tags: ['إيطالي', 'فاخر', 'كلاسيكي', 'تصميم'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 72,
        name: 'Muse',
        category: 'مقهى متخصص',
        description: 'يجمع بين القهوة والكتب والفن، مكان ملهم وهادئ.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Muse+Coffee+and+Books+Shuwaikh',
        imageUrl: '',
        tags: ['كتب', 'فن', 'هدوء', 'ملهم', 'ثقافة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 73,
        name: 'Véranda',
        category: 'مقهى متخصص',
        description: 'جلسات خارجية رائعة وأجواء تشبه المقاهي الأوروبية.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Veranda+Cafe+The+Avenues',
        imageUrl: '',
        tags: ['جلسات خارجية', 'أوروبي', 'رائع'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 74,
        name: 'Over Jar',
        category: 'مقهى متخصص',
        description: 'لعشاق الشوكولاتة، يقدم حلويات غنية ومشروبات مبتكرة.',
        locationName: 'الفحيحيل',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Over+Jar+Al+Kout+Mall',
        imageUrl: '',
        tags: ['شوكولاتة', 'حلويات', 'غني', 'مبتكر'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 75,
        name: 'Leto',
        category: 'مقهى متخصص',
        description: 'مقهى لندني شهير بكيكة الحليب والزعفران والحلويات الشهية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=LETO+Caffe+The+Avenues',
        imageUrl: '',
        tags: ['حلويات', 'كيك', 'لندني', 'مشهور'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 76,
        name: 'The Chocolate Bar',
        category: 'مقهى متخصص',
        description: 'وجهة كلاسيكية للحلويات والمشروبات، مناسب جميع الأذواق.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Chocolate+Bar+Al+Bidaa',
        imageUrl: '',
        tags: ['شوكولاتة', 'حلويات', 'كلاسيكي', 'عائلي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 77,
        name: 'Vardo',
        category: 'مقهى متخصص',
        description: 'مقهى ومخبز يقدم معجنات طازجة وقهوة لذيذة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vardo+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['مخبز', 'معجنات', 'طازج', 'قهوة'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 78,
        name: 'Chapter',
        category: 'مقهى متخصص',
        description: 'مكان هادئ ومثالي للقراءة أو العمل مع كوب قهوة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Chapter+Coffee+Shuwaikh',
        imageUrl: '',
        tags: ['هدوء', 'قراءة', 'عمل', 'قهوة'],
        suitableFor: ['individual'],
    },
    {
        id: 79,
        name: 'Before Chocolate',
        category: 'مقهى متخصص',
        description: 'متخصص في الشوكولاتة الساخنة والحلويات المبتكرة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Before+Chocolate+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['شوكولاتة', 'ساخنة', 'حلويات', 'مبتكر'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 80,
        name: 'Mood Coffee Bar',
        category: 'مقهى متخصص',
        description: 'مقهى صغير يقدم قهوة ممتازة وأجواء شبابية.',
        locationName: 'الشعب البحري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mood+Coffee+Bar+Shaab+Al+Bahri',
        imageUrl: '',
        tags: ['قهوة', 'صغير', 'شبابي'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 81,
        name: "Toby's Estate (الأفنيوز)",
        category: 'مقهى متخصص',
        description: 'فرع آخر للعلامة الشهيرة في قلب الأفنيوز.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Toby\'s+Estate+Coffee+The+Avenues',
        imageUrl: '',
        tags: ['قهوة', 'مشهور', 'تسوق', 'شبابي'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 82,
        name: 'Dose Cafe',
        category: 'مقهى متخصص',
        description: 'سلسلة مقاهي مشهورة بقهوتها الباردة والمبتكرة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dose+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['قهوة باردة', 'مبتكر', 'مشهور', 'شبابي'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 83,
        name: 'Bartone',
        category: 'مقهى متخصص',
        description: 'مقهى ومحمصة في برج الحمراء بإطلالة رائعة.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bartone+Cafe+Al+Hamra+Tower',
        imageUrl: '',
        tags: ['إطلالة', 'محمصة', 'قهوة', 'راقي'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 84,
        name: 'La Nuit',
        category: 'مقهى متخصص',
        description: 'مقهى أنيق بأجواء فرنسية في قلب العاصمة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Nuit+Cafe+Kuwait+City',
        imageUrl: '',
        tags: ['أنيق', 'فرنسي', 'عصري'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 85,
        name: 'Crush Cafe',
        category: 'مقهى متخصص',
        description: 'مقهى صغير ومميز في منطقة السرة.',
        locationName: 'السرة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Crush+Cafe+Surra',
        imageUrl: '',
        tags: ['صغير', 'مميز', 'قهوة', 'محلي'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 86,
        name: 'OIA',
        category: 'مقهى متخصص',
        description: 'مستوحى من جزيرة سانتوريني اليونانية، أجواء صيفية رائعة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=OIA+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['صيفي', 'يوناني', 'تصميم', 'رائع'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 87,
        name: 'Keys Coffee',
        category: 'مقهى متخصص',
        description: 'قهوة مختصة ممتازة في مكان هادئ.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Keys+Coffee+Shop+Shuwaikh',
        imageUrl: '',
        tags: ['قهوة', 'مختصة', 'هدوء', 'ممتاز'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 88,
        name: 'Street Cafe',
        category: 'مقهى متخصص',
        description: 'مقهى درايف ثرو شهير ومناسب لقهوة سريعة.',
        locationName: 'العديلية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Street+Cafe+Adailiya',
        imageUrl: '',
        tags: ['درايف ثرو', 'سريع', 'قهوة', 'مشهور'],
        suitableFor: ['individual'],
    },
    {
        id: 89,
        name: '% Arabica (حديقة الشهيد)',
        category: 'مقهى متخصص',
        description: 'فرع آخر بإطلالة جميلة على حديقة الشهيد.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=%+Arabica+Al+Shaheed+Park',
        imageUrl: '',
        tags: ['قهوة', 'مختصة', 'إطلالة', 'حديقة', 'جميل'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 90,
        name: 'Earth Roastery',
        category: 'مقهى متخصص',
        description: 'محمصة ومقهى يقدم قهوة عضوية عالية الجودة.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Earth+Roastery+Cafe+Salmiya',
        imageUrl: '',
        tags: ['عضوي', 'محمصة', 'جودة', 'صحي'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 91,
        name: '?Got Cookie',
        category: 'مقهى متخصص',
        description: 'متخصص في الكوكيز الطازج والقهوة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Got+Cookie?+Shuwaikh',
        imageUrl: '',
        tags: ['كوكيز', 'حلويات', 'طازج', 'قهوة'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 92,
        name: 'Uptown',
        category: 'مقهى متخصص',
        description: 'مقهى صغير ومميز في منطقة أبو الحصانية.',
        locationName: 'أبو الحصانية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Uptown+Cafe+Abu+Al+Hasaniya',
        imageUrl: '',
        tags: ['صغير', 'مميز', 'محلي'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 93,
        name: 'The November Bakery',
        category: 'مقهى متخصص',
        description: 'مخبز ومقهى يقدم حلويات رائعة وكيكات مميزة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+November+Bakery+Kuwait+City',
        imageUrl: '',
        tags: ['مخبز', 'حلويات', 'كيك', 'مميز'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 94,
        name: 'Vibes',
        category: 'مقهى متخصص',
        description: 'أجواء شبابية وموسيقى رائعة مع قهوة مميزة.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vibes+Cafe+Al+Bidaa',
        imageUrl: '',
        tags: ['شبابي', 'موسيقى', 'حيوي'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 95,
        name: 'Origin',
        category: 'مقهى متخصص',
        description: 'محمصة ومقهى يركز على أصل حبوب القهوة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Origin+Coffee+Roasters+Kuwait+City',
        imageUrl: '',
        tags: ['محمصة', 'قهوة', 'أصل واحد', 'جودة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 96,
        name: 'Mika',
        category: 'مقهى متخصص',
        description: 'مقهى ياباني صغير يقدم الماتشا والقهوة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mika+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['ياباني', 'ماتشا', 'صغير', 'قهوة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 97,
        name: '20 Grams',
        category: 'مقهى متخصص',
        description: 'مقهى متخصص يقدم قهوة وحلويات مبتكرة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=20+Grams+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['قهوة', 'حلويات', 'مبتكر'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 98,
        name: 'Starbucks Reserve (الأفنيوز)',
        category: 'مقهى متخصص',
        description: 'تجربة ستاربكس الفاخرة مع أنواع قهوة نادرة.',
        locationName: 'الري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Starbucks+Reserve+The+Avenues+Kuwait',
        imageUrl: '',
        tags: ['قهوة', 'فاخر', 'نادر', 'ستاربكس'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 99,
        name: "L'ETO (الكوت مول)",
        category: 'مقهى متخصص',
        description: 'فرع آخر للمقهى اللندني الشهير بالحلويات.',
        locationName: 'الفحيحيل',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=LETO+Caffe+Al+Kout+Mall',
        imageUrl: '',
        tags: ['حلويات', 'كيك', 'لندني', 'مشهور'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 100,
        name: 'White',
        category: 'مقهى متخصص',
        description: 'مقهى بتصميم أبيض نقي وأجواء هادئة.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=White+Cafe+Salmiya',
        imageUrl: '',
        tags: ['تصميم', 'أبيض', 'هدوء', 'نقي'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 101,
        name: 'Location',
        category: 'مقهى متخصص',
        description: 'قهوة ممتازة ومكان مناسب للعمل أو الدراسة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Location+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['عمل', 'دراسة', 'قهوة', 'ممتاز'],
        suitableFor: ['individual'],
    },
    {
        id: 102,
        name: 'Ambit',
        category: 'مقهى متخصص',
        description: 'مقهى بتصميم بسيط وعصري يقدم قهوة مختصة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ambit+Cafe+Shuwaikh',
        imageUrl: '',
        tags: ['بسيط', 'عصري', 'قهوة مختصة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 103,
        name: 'Sons of Adam',
        category: 'مقهى متخصص',
        description: 'مقهى بنكهة محلية وهوية فريدة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sons+of+Adam+Kuwait+City',
        imageUrl: '',
        tags: ['محلي', 'هوية', 'فريد'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 104,
        name: 'So Matcha',
        category: 'مقهى متخصص',
        description: 'متخصص في جميع أنواع مشروبات الماتشا.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=So+Matcha+Shuwaikh',
        imageUrl: '',
        tags: ['ماتشا', 'صحي', 'متخصص'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 105,
        name: 'Muse Lounge',
        category: 'مقهى متخصص',
        description: 'فرع آخر لمقهى ميوز بأجواء مختلفة.',
        locationName: 'الخالدية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Muse+Lounge+Khaldiya',
        imageUrl: '',
        tags: ['كتب', 'فن', 'هدوء', 'ثقافة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 106,
        name: "L'éclair de Génie",
        category: 'مقهى متخصص',
        description: 'متخصص في حلوى الإكلير الفرنسية الفاخرة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=L\'eclair+de+Genie+The+Avenues',
        imageUrl: '',
        tags: ['حلويات', 'إكلير', 'فرنسي', 'فاخر'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 107,
        name: 'Wish',
        category: 'مقهى متخصص',
        description: 'مقهى صغير وحميمي يقدم قهوة ممتازة.',
        locationName: 'اليرموك',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Wish+Cafe+Yarmouk',
        imageUrl: '',
        tags: ['صغير', 'حميمي', 'قهوة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 108,
        name: 'DRVN',
        category: 'مقهى متخصص',
        description: 'مقهى ومطعم يجمع بين حب السيارات والقهوة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=DRVN+Coffee+Shuwaikh',
        imageUrl: '',
        tags: ['سيارات', 'قهوة', 'مطعم', 'فريد'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 109,
        name: 'Fuel',
        category: 'مقهى متخصص',
        description: 'مقهى صغير ومشهور بمشروب "سبانيش لاتيه".',
        locationName: 'الجابرية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Fuel+Specialty+Coffee+Jabriya',
        imageUrl: '',
        tags: ['سبانيش لاتيه', 'مشهور', 'قهوة'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 110,
        name: 'The nineteen sixty one',
        category: 'مقهى متخصص',
        description: 'مقهى بأجواء كلاسيكية وتصميم أنيق.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+nineteen+sixty+one+Shuwaikh',
        imageUrl: '',
        tags: ['كلاسيكي', 'أنيق', 'تصميم'],
        suitableFor: ['couple', 'group'],
    },
    // --- مطاعم كويتية (111-124) ---
    {
        id: 111,
        name: 'فريج صويلح',
        category: 'مطعم كويتي',
        description: 'تجربة كويتية أصيلة في أجواء شعبية ممتعة.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Freej+Swaileh+Restaurant+Salmiya',
        imageUrl: '',
        tags: ['كويتي', 'شعبي', 'أصالة', 'عائلي'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 112,
        name: 'دار حمد',
        category: 'مطعم كويتي',
        description: 'مطعم كويتي فاخر بإطلالة بحرية وتصميم تراثي عصري.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dar+Hamad+Restaurant+Salmiya',
        imageUrl: '',
        tags: ['كويتي', 'فاخر', 'إطلالة بحرية', 'تراث', 'عصري'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 113,
        name: 'بيت ديكسون',
        category: 'مطعم كويتي',
        description: 'يقدم الأكل الكويتي بلمسة عصرية في أجواء تاريخية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dickson+House+Kuwait+City',
        imageUrl: '',
        tags: ['كويتي', 'عصري', 'تاريخي', 'لمسة خاصة'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 114,
        name: 'مطعم بزة',
        category: 'مطعم كويتي',
        description: 'أطباق كويتية تقليدية في أجواء عائلية مريحة.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bazza+Kuwaiti+Restaurant+Al+Bidaa',
        imageUrl: '',
        tags: ['كويتي', 'تقليدي', 'عائلي', 'مريح'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 115,
        name: 'شيرين بانو',
        category: 'مطعم كويتي',
        description: 'للمأكولات الإيرانية الأصيلة والكباب اللذيذ.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sheerin+Banu+Restaurant+Salmiya',
        imageUrl: '',
        tags: ['إيراني', 'كباب', 'أصالة'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 116,
        name: 'مطعم ميس الغانم',
        category: 'مطعم كويتي',
        description: 'من أقدم وأشهر المطاعم اللبنانية في الكويت.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mais+Alghanim+Restaurant+Sharq',
        imageUrl: '',
        tags: ['لبناني', 'مشويات', 'قديم', 'مشهور'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 117,
        name: 'فيلا فيروز',
        category: 'مطعم كويتي',
        description: 'مطعم لبناني راقٍ يقدم أطباقاً تقليدية بجودة عالية.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Villa+Fayrouz+The+Avenues',
        imageUrl: '',
        tags: ['لبناني', 'راقي', 'تقليدي', 'جودة عالية'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 118,
        name: 'فريج عقاب',
        category: 'مطعم كويتي',
        description: 'مطعم شعبي في سوق المباركية يقدم أطباقاً كويتية أصيلة.',
        locationName: 'القبلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Freej+Agab+Mubarakiya',
        imageUrl: '',
        tags: ['كويتي', 'شعبي', 'سوق المباركية', 'أصالة'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 119,
        name: 'الشمم',
        category: 'مطعم كويتي',
        description: 'مطعم مشويات شعبي مشهور في سوق المباركية.',
        locationName: 'القبلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Al-Shamem+Restaurant+Mubarakiya',
        imageUrl: '',
        tags: ['مشويات', 'شعبي', 'سوق المباركية', 'مشهور'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 120,
        name: 'Babel',
        category: 'مطعم كويتي',
        description: 'مطعم لبناني فاخر بإطلالة بحرية وتقديم مبتكر.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Babel+Restaurant+Kuwait',
        imageUrl: '',
        tags: ['لبناني', 'فاخر', 'إطلالة بحرية', 'مبتكر'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 121,
        name: 'حمسة',
        category: 'مطعم كويتي',
        description: 'مطعم كويتي عصري يقدم الريوق (الفطور) الكويتي بلمسة خاصة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hamsa+Restaurant+Shuwaikh',
        imageUrl: '',
        tags: ['كويتي', 'فطور', 'ريوق', 'عصري', 'لمسة خاصة'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 122,
        name: "Sultan's Chef",
        category: 'مطعم كويتي',
        description: 'مطعم تركي فاخر متخصص في اللحوم والستيك.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sultan\'s+Chef+Kuwait+City',
        imageUrl: '',
        tags: ['تركي', 'فاخر', 'لحوم', 'ستيك'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 123,
        name: 'مطعم مطبق زبيدي',
        category: 'مطعم كويتي',
        description: 'متخصص في طبق المطبق الكويتي الشهير.',
        locationName: 'حولي',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mutabbaq+Zubaidi+Restaurant+Hawally',
        imageUrl: '',
        tags: ['كويتي', 'مطبق', 'زبيدي', 'شعبي'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 124,
        name: 'مطعم شرق أوسطي Leila min Lebnen',
        category: 'مطعم كويتي',
        description: 'مطعم لبناني بأجواء منزلية دافئة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Leila+min+Lebnen+The+Avenues',
        imageUrl: '',
        tags: ['لبناني', 'منزلي', 'دافئ'],
        suitableFor: ['couple', 'family', 'group'],
    },
    // --- مطاعم إيطالية (125-140) ---
    {
        id: 125,
        name: 'Emirgan Sutis',
        category: 'مطعم إيطالي',
        description: 'مطعم تركي يقدم الفطور والحلويات التركية الأصيلة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Emirgan+Sutis+The+Avenues',
        imageUrl: '',
        tags: ['تركي', 'فطور', 'حلويات', 'أصالة'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 126,
        name: 'Bice',
        category: 'مطعم إيطالي',
        description: 'مطعم إيطالي راقٍ يقدم أطباقاً كلاسيكية بجودة عالية.',
        locationName: 'مجمع الحمراء',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bice+Restaurant+Al+Hamra+Tower',
        imageUrl: '',
        tags: ['إيطالي', 'راقي', 'كلاسيكي', 'جودة عالية'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 127,
        name: 'Trapani',
        category: 'مطعم إيطالي',
        description: 'أجواء إيطالية ريفية وأطباق بيتزا وباستا شهية.',
        locationName: 'مجمع الحمراء',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Trapani+Restaurant+Al+Hamra+Tower',
        imageUrl: '',
        tags: ['إيطالي', 'ريفي', 'بيتزا', 'باستا'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 128,
        name: 'Pizza Express',
        category: 'مطعم إيطالي',
        description: 'بيتزا على الطريقة الإيطالية الكلاسيكية بخيار مضمون ولذيذ.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=PizzaExpress+Al+Bidaa',
        imageUrl: '',
        tags: ['بيتزا', 'إيطالي', 'كلاسيكي', 'لذيذ'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 129,
        name: 'Nino',
        category: 'مطعم إيطالي',
        description: 'يجمع بين الأطباق الإيطالية والعالمية في أجواء حيوية.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Nino+Restaurant+Al+Bidaa',
        imageUrl: '',
        tags: ['إيطالي', 'عالمي', 'حيوي'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 130,
        name: 'Melenzanè',
        category: 'مطعم إيطالي',
        description: 'مطعم إيطالي مبتكر يقدم أطباقاً فريدة مثل ريزوتو الفطر.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Melenzane+The+Avenues',
        imageUrl: '',
        tags: ['إيطالي', 'مبتكر', 'فريد', 'ريزوتو'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 131,
        name: 'Signor Sassi',
        category: 'مطعم إيطالي',
        description: 'مطعم إيطالي فاخر من لندن، تجربة طعام استثنائية.',
        locationName: 'فندق سيمفوني',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Signor+Sassi+Kuwait',
        imageUrl: '',
        tags: ['إيطالي', 'فاخر', 'لندني', 'استثنائي'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 132,
        name: 'Lorenzo',
        category: 'مطعم إيطالي',
        description: 'مطعم إيطالي كلاسيكي وأجواء هادئة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Lorenzo+Restaurant+Kuwait+City',
        imageUrl: '',
        tags: ['إيطالي', 'كلاسيكي', 'هدوء'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 133,
        name: 'Gia',
        category: 'مطعم إيطالي',
        description: 'مطعم ومقهى إيطالي عصري في العاصمة مول.',
        locationName: 'العاصمة مول',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Gia+Kuwait+Assima+Mall',
        imageUrl: '',
        tags: ['إيطالي', 'عصري', 'مقهى', 'مطعم'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 134,
        name: 'Cipriani',
        category: 'مطعم إيطالي',
        description: 'اسم عالمي فاخر يقدم تجربة طعام إيطالية راقية.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cipriani+Dolci+The+Avenues',
        imageUrl: '',
        tags: ['إيطالي', 'فاخر', 'عالمي', 'راقي'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 135,
        name: 'Vigonovo',
        category: 'مطعم إيطالي',
        description: 'مطعم متخصص في المأكولات الإيطالية الشمالية.',
        locationName: 'الفنطاس',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vigonovo+Restaurant+Fintas',
        imageUrl: '',
        tags: ['إيطالي', 'شمالي', 'متخصص'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 136,
        name: 'Olio',
        category: 'مطعم إيطالي',
        description: 'بيتزا نابولية أصيلة في فندق الجميرا.',
        locationName: 'المسيلة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Olio+Trattoria+Italiana+Jumeirah+Messilah+Beach+Hotel',
        imageUrl: '',
        tags: ['بيتزا', 'نابولي', 'أصيلة', 'فندق'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 137,
        name: 'Riccardo',
        category: 'مطعم إيطالي',
        description: 'مطعم إيطالي راقٍ في فندق شيراتون الكويت.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Riccardo+Restaurant+Sheraton+Kuwait',
        imageUrl: '',
        tags: ['إيطالي', 'راقي', 'فندق', 'فاخر'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 138,
        name: 'The North Slice',
        category: 'مطعم إيطالي',
        description: 'متخصص في البيتزا النيويوركية بالقطعة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+North+Slice+Shuwaikh',
        imageUrl: '',
        tags: ['بيتزا', 'نيويوركي', 'قطعة', 'سريع'],
        suitableFor: ['individual', 'group'],
    },
    {
        id: 139,
        name: '400 Gradi',
        category: 'مطعم إيطالي',
        description: 'بيتزا نابولية حائز على جوائز عالمية.',
        locationName: 'ذا جيت مول',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=400+Gradi+The+Gate+Mall',
        imageUrl: '',
        tags: ['بيتزا', 'نابولي', 'عالمي', 'جوائز'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 140,
        name: 'Solo Pizza Napulitana',
        category: 'مطعم إيطالي',
        description: 'من أوائل مطاعم البيتزا النابولية في الكويت.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=SOLO+Pizza+Napulitana+Shuwaikh',
        imageUrl: '',
        tags: ['بيتزا', 'نابولي', 'قديم', 'أصالة'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    // --- مطاعم آسيوية (141-160) ---
    {
        id: 141,
        name: 'Maki',
        category: 'مطعم آسيوي',
        description: 'مطعم ياباني مبتكر يقدم أطباق سوشي ومأكولات يابانية فريدة.',
        locationName: 'مروج',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Maki+Murouj+Kuwait',
        imageUrl: '',
        tags: ['ياباني', 'سوشي', 'مبتكر', 'فريد'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 142,
        name: 'Tatami',
        category: 'مطعم آسيوي',
        description: 'تجربة يابانية راقية وأصيلة في قلب المدينة.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tatami+Japanese+Restaurant+Kuwait+City',
        imageUrl: '',
        tags: ['ياباني', 'راقي', 'أصالة'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 143,
        name: 'Wok Hay',
        category: 'مطعم آسيوي',
        description: 'مطعم صيني عصري يقدم أطباقاً لذيذة وسريعة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Wok+Hay+The+Avenues',
        imageUrl: '',
        tags: ['صيني', 'عصري', 'سريع', 'ووك'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 144,
        name: 'White Robata',
        category: 'مطعم آسيوي',
        description: 'مشاوي يابانية (روباتا) في أجواء فاخرة بمركز جابر الثقافي.',
        locationName: 'مركز جابر الثقافي',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=White+Robata+JACC+Kuwait',
        imageUrl: '',
        tags: ['ياباني', 'مشاوي', 'روباتا', 'فاخر'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 145,
        name: "Asha's",
        category: 'مطعم آسيوي',
        description: 'مطعم هندي فاخر للمطربة آشا بهوسل، يقدم أطباقاً تقليدية بلمسة عصرية.',
        locationName: 'مارينا كريست',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Asha\'s+Restaurant+Marina+Crescent',
        imageUrl: '',
        tags: ['هندي', 'فاخر', 'تقليدي', 'عصري'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 146,
        name: 'Ora',
        category: 'مطعم آسيوي',
        description: 'مطعم ياباني يقدم أطباقاً صغيرة للمشاركة.',
        locationName: 'العاصمة مول',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ora+Japanese+Tapas+Assima+Mall',
        imageUrl: '',
        tags: ['ياباني', 'مشاركة', 'صغير'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 147,
        name: 'Kei',
        category: 'مطعم آسيوي',
        description: 'مطعم ياباني كلاسيكي وتقليدي في فندق ماريوت.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Kei+Restaurant+JW+Marriott+Kuwait+City',
        imageUrl: '',
        tags: ['ياباني', 'كلاسيكي', 'تقليدي', 'فندق'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 148,
        name: 'Vine',
        category: 'مطعم آسيوي',
        description: 'مطعم هندي يقدم أطباقاً مبتكرة في أجواء عصرية.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vine+Restaurant+Al+Bidaa',
        imageUrl: '',
        tags: ['هندي', 'مبتكر', 'عصري'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 149,
        name: 'Wasabi',
        category: 'مطعم آسيوي',
        description: 'مطعم ياباني عصري مشهور بأطباقه اللذيذة.',
        locationName: 'مجمع الحمراء',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Wasabi+Al+Hamra+Tower',
        imageUrl: '',
        tags: ['ياباني', 'عصري', 'مشهور', 'سوشي'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 150,
        name: 'Rock House Slider',
        category: 'مطعم آسيوي',
        description: 'مطعم ياباني متخصص في السلايدرز بلمسة يابانية.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rock+House+Slider+The+Avenues',
        imageUrl: '',
        tags: ['سلايدر', 'ياباني', 'مبتكر'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 151,
        name: "PF Chang's",
        category: 'مطعم آسيوي',
        description: 'مطعم صيني أمريكي شهير بأطباق مثل "داينمايت شرمب".',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=P.F.+Chang\'s+The+Avenues',
        imageUrl: '',
        tags: ['صيني', 'أمريكي', 'مشهور', 'داينمايت شرمب'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 152,
        name: 'My Toy',
        category: 'مطعم آسيوي',
        description: 'مزيج من المأكولات الآسيوية في مكان واحد.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=My+Toy+Restaurant+The+Avenues',
        imageUrl: '',
        tags: ['آسيوي', 'متنوع', 'مزيج'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 153,
        name: 'B+F',
        category: 'مطعم آسيوي',
        description: 'يجمع بين المطبخ الياباني والهندي والأمريكي.',
        locationName: 'مروج',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=B+F+Restaurant+Murouj',
        imageUrl: '',
        tags: ['ياباني', 'هندي', 'أمريكي', 'متنوع'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 154,
        name: 'Sakura',
        category: 'مطعم آسيوي',
        description: 'مطعم ياباني تقليدي يقدم تجربة السوشي والتبنياكي.',
        locationName: 'فندق كراون بلازا',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sakura+Japanese+Restaurant+Crowne+Plaza+Kuwait',
        imageUrl: '',
        tags: ['ياباني', 'تقليدي', 'سوشي', 'تبنياكي'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 155,
        name: 'Dai Forni',
        category: 'مطعم آسيوي',
        description: 'مطعم إيطالي-آسيوي في فندق فورسيزونز بإطلالة بانورامية.',
        locationName: 'شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dai+Forni+Restaurant+Four+Seasons+Kuwait',
        imageUrl: '',
        tags: ['إيطالي', 'آسيوي', 'فاخر', 'إطلالة'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 156,
        name: 'Ubon',
        category: 'مطعم آسيوي',
        description: 'مطعم تايلاندي أصيل في أجواء عصرية.',
        locationName: 'مروج',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ubon+Thai+Restaurant+Murouj',
        imageUrl: '',
        tags: ['تايلاندي', 'أصيل', 'عصري'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 157,
        name: 'Oishii Sushi',
        category: 'مطعم آسيوي',
        description: 'مطعم سوشي يقدم أطباقاً مبتكرة وذات جودة عالية.',
        locationName: 'الشعب البحري',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Oishii+Sushi+Restaurant+Shaab+Al+Bahri',
        imageUrl: '',
        tags: ['سوشي', 'مبتكر', 'جودة عالية'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 158,
        name: 'Namaste',
        category: 'مطعم آسيوي',
        description: 'مطعم هندي بسيط يقدم أطباقاً لذيذة بأسعار معقولة.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Namaste+Indian+Restaurant+Salmiya',
        imageUrl: '',
        tags: ['هندي', 'بسيط', 'لذيذ', 'اقتصادي'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 159,
        name: 'Wagamama',
        category: 'مطعم آسيوي',
        description: 'سلسلة عالمية تقدم الأكل الياباني السريع مثل الرامن والنودلز.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Wagamama+The+Avenues',
        imageUrl: '',
        tags: ['ياباني', 'سريع', 'رامن', 'نودلز'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 160,
        name: 'China Garden',
        category: 'مطعم آسيوي',
        description: 'مطعم صيني كلاسيكي معروف بأطباقه الأصيلة.',
        locationName: 'فندق راديسون بلو',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=China+Garden+Restaurant+Radisson+Blu+Kuwait',
        imageUrl: '',
        tags: ['صيني', 'كلاسيكي', 'أصيل'],
        suitableFor: ['couple', 'family', 'group'],
    },
    // --- مطاعم أمريكية (161-175) ---
    {
        id: 161,
        name: 'Slider Station',
        category: 'مطعم أمريكي',
        description: 'من أشهر مطاعم البرجر المبتكرة في الكويت، بأجوائه الصناعية.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Slider+Station+Salmiya',
        imageUrl: '',
        tags: ['برجر', 'سلايدر', 'مبتكر', 'صناعي'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 162,
        name: 'OFK - Open Flame Kitchen',
        category: 'مطعم أمريكي',
        description: 'مطعم أمريكي عصري يقدم البرجر والستيك بأسلوب مميز.',
        locationName: 'مول 360',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Open+Flame+Kitchen+360+Mall',
        imageUrl: '',
        tags: ['أمريكي', 'عصري', 'برجر', 'ستيك'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 163,
        name: 'The Cheesecake Factory',
        category: 'مطعم أمريكي',
        description: 'قائمة طعام ضخمة تناسب جميع الأذواق وتشيكلة "تشيزكيك" أسطورية.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Cheesecake+Factory+The+Avenues',
        imageUrl: '',
        tags: ['عائلي', 'قائمة كبيرة', 'تشيزكيك', 'أمريكي'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 164,
        name: 'Shake Shack',
        category: 'مطعم أمريكي',
        description: 'برجر كلاسيكي بسيط ولذيذ مع بطاطس "كرينكل" الشهيرة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Shake+Shack+The+Avenues',
        imageUrl: '',
        tags: ['برجر', 'كلاسيكي', 'بطاطس', 'سريع'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 165,
        name: 'Thinnies',
        category: 'مطعم أمريكي',
        description: 'متخصص في برجر "سماش" الرقيق واللذيذ.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Thinnies+Burger+Shuwaikh',
        imageUrl: '',
        tags: ['برجر', 'سماش', 'رقيق', 'لذيذ'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 166,
        name: 'Five Guys',
        category: 'مطعم أمريكي',
        description: 'برجر قابل للتخصيص بالكامل مع بطاطس طازجة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Five+Guys+The+Avenues',
        imageUrl: '',
        tags: ['برجر', 'تخصيص', 'بطاطس', 'طازج'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 167,
        name: 'Texas Roadhouse',
        category: 'مطعم أمريكي',
        description: 'مطعم ستيك هاوس أمريكي بأجواء ريفية ممتعة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Texas+Roadhouse+The+Avenues',
        imageUrl: '',
        tags: ['ستيك', 'أمريكي', 'ريفي', 'لحوم'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 168,
        name: "Raising Cane's",
        category: 'مطعم أمريكي',
        description: 'متخصص في دجاج الفيليه المقرمش، قائمة بسيطة وممتازة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Raising+Cane\'s+The+Avenues',
        imageUrl: '',
        tags: ['دجاج', 'مقرمش', 'بسيط', 'سريع'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 169,
        name: 'Fuddruckers',
        category: 'مطعم أمريكي',
        description: 'برجر أمريكي كلاسيكي مع "بار" سلطات وإضافات مفتوح.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Fuddruckers+Salmiya',
        imageUrl: '',
        tags: ['برجر', 'كلاسيكي', 'سلطات', 'إضافات'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 170,
        name: 'Johnny Rockets',
        category: 'مطعم أمريكي',
        description: 'أجواء الخمسينات الأمريكية مع برجر وشيكات الحليب.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Johnny+Rockets+Salmiya',
        imageUrl: '',
        tags: ['أمريكي', 'خمسينات', 'برجر', 'ميلك شيك'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 171,
        name: 'The Pit',
        category: 'مطعم أمريكي',
        description: 'متخصص في اللحوم المدخنة على الطريقة الأمريكية (الباربيكيو).',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Pit+BBQ+Shuwaikh',
        imageUrl: '',
        tags: ['لحوم', 'مدخن', 'باربيكيو', 'أمريكي'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 172,
        name: 'Fatburger',
        category: 'مطعم أمريكي',
        description: 'برجر أمريكي كلاسيكي لذيذ.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Fatburger+Salmiya',
        imageUrl: '',
        tags: ['برجر', 'أمريكي', 'كلاسيكي', 'لذيذ'],
        suitableFor: ['individual', 'family', 'group'],
    },
    {
        id: 173,
        name: "Buffalo's",
        category: 'مطعم أمريكي',
        description: 'مشهور بأجنحة الدجاج (بافلو وينجز) والبرجر.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Buffalo\'s+Cafe+The+Avenues',
        imageUrl: '',
        tags: ['أجنحة دجاج', 'بافلو', 'برجر', 'أمريكي'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 174,
        name: 'Burger Boutique',
        category: 'مطعم أمريكي',
        description: 'مطعم برجر راقٍ يقدم خيارات مبتكرة وعضوية.',
        locationName: 'مروج',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Burger+Boutique+Murouj',
        imageUrl: '',
        tags: ['برجر', 'راقي', 'مبتكر', 'عضوي'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 175,
        name: "Momo's",
        category: 'مطعم أمريكي',
        description: 'برجر بسيط ولذيذ يحبه الكثيرون.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Momo\'s+Burger+Shuwaikh',
        imageUrl: '',
        tags: ['برجر', 'بسيط', 'لذيذ', 'مشهور'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    // --- مطاعم فطور وعائلي (176-200) ---
    {
        id: 176,
        name: 'The Early Bird',
        category: 'مطعم فطور وعائلي',
        description: 'وجهة فطور أمريكية كلاسيكية مشهورة بالبانكيك والدجاج والوافل.',
        locationName: 'الفنطاس',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Early+Bird+Fintas',
        imageUrl: '',
        tags: ['فطور', 'أمريكي', 'بانكيك', 'وافل'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 177,
        name: 'Baker & Spice',
        category: 'مطعم فطور وعائلي',
        description: 'تجربة فطور راقية مع إطلالة بحرية.',
        locationName: 'سوق شرق',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Baker+and+Spice+Souq+Sharq',
        imageUrl: '',
        tags: ['فطور', 'راقي', 'إطلالة بحرية', 'عائلي'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 178,
        name: 'Dean & DeLuca',
        category: 'مطعم فطور وعائلي',
        description: 'ديلي نيويوركي راقٍ، مثالي للفطور أو غداء خفيف.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Dean+and+DeLuca+The+Avenues',
        imageUrl: '',
        tags: ['فطور', 'غداء', 'ديلي', 'نيويوركي', 'راقي'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 179,
        name: 'Balthazar',
        category: 'مطعم فطور وعائلي',
        description: 'مطعم فرنسي أنيق يقدم تجربة فطور فاخرة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Balthazar+Restaurant+The+Avenues',
        imageUrl: '',
        tags: ['فطور', 'فرنسي', 'أنيق', 'فاخر'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 180,
        name: 'Bürk',
        category: 'مطعم فطور وعائلي',
        description: 'مطعم ستيك هاوس فاخر يقدم تجربة طعام استثنائية.',
        locationName: 'العاصمة مول',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Burk+Steakhouse+Assima+Mall',
        imageUrl: '',
        tags: ['ستيك', 'فاخر', 'لحوم', 'عشاء'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 181,
        name: 'Cocoa Room',
        category: 'مطعم فطور وعائلي',
        description: 'من أشهر وجهات الفطور في الكويت، أطباق مبتكرة ولذيذة.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cocoa+Room+Kuwait+City',
        imageUrl: '',
        tags: ['فطور', 'مشهور', 'مبتكر', 'لذيذ'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 182,
        name: 'Breakfast Club',
        category: 'مطعم فطور وعائلي',
        description: 'قائمة فطور متنوعة ترضي جميع الأذواق في أجواء مريحة.',
        locationName: 'المهبولة',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Breakfast+Club+Mahboula',
        imageUrl: '',
        tags: ['فطور', 'متنوع', 'مريح', 'عائلي'],
        suitableFor: ['individual', 'couple', 'family', 'group'],
    },
    {
        id: 183,
        name: 'Madison & Heig',
        category: 'مطعم فطور وعائلي',
        description: 'مطعم ومخبز يقدم الفطور والحلويات لمسة خاصة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Madison+and+Heig+The+Avenues',
        imageUrl: '',
        tags: ['فطور', 'حلويات', 'مخبز', 'لمسة خاصة'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 184,
        name: 'Street by Al Makan',
        category: 'مطعم فطور وعائلي',
        description: 'يقدم أكل الشوارع من حول العالم في مكان واحد.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Street+by+Al+Makan+Shuwaikh',
        imageUrl: '',
        tags: ['أكل شوارع', 'متنوع', 'عالمي'],
        suitableFor: ['individual', 'couple', 'group'],
    },
    {
        id: 185,
        name: "The Butcher's Den",
        category: 'مطعم فطور وعائلي',
        description: 'مطعم ستيك هاوس متخصص في قطعية اللحم عالية الجودة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Butcher\'s+Den+Shuwaikh',
        imageUrl: '',
        tags: ['ستيك', 'لحوم', 'جودة عالية', 'متخصص'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 186,
        name: 'La Brasa',
        category: 'مطعم فطور وعائلي',
        description: 'مطعم إسباني يقدم تجربة التاباس والأطباق الإسبانية.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Brasa+The+Avenues',
        imageUrl: '',
        tags: ['إسباني', 'تاباس', 'عشاء'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 187,
        name: 'F&N',
        category: 'مطعم فطور وعائلي',
        description: 'يقدم مأكولات عالمية متنوعة في أجواء أنيقة.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=F+and+N+Restaurant+The+Avenues',
        imageUrl: '',
        tags: ['عالمي', 'متنوع', 'أنيق'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 188,
        name: 'Angelina Paris',
        category: 'مطعم فطور وعائلي',
        description: 'مقهى ومطعم فرنسي فاخر مشهور بالشوكولاتة الساخنة والحلويات المونت بلانك.',
        locationName: 'الأفنيوز',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Angelina+Paris+The+Avenues',
        imageUrl: '',
        tags: ['فرنسي', 'فاخر', 'شوكولاتة', 'حلويات'],
        suitableFor: ['couple', 'group'],
    },
    {
        id: 189,
        name: 'Eggcellent',
        category: 'مطعم فطور وعائلي',
        description: 'متخصص في سندويشات البيض للفطور بطريقة مبتكرة.',
        locationName: 'الدعية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Eggcellent+Daiya',
        imageUrl: '',
        tags: ['فطور', 'بيض', 'سندويشات', 'مبتكر'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 190,
        name: 'Zaatar w Zeit',
        category: 'مطعم فطور وعائلي',
        description: 'خيار سريع وصحي للفطور والغداء، من أشهرها المناقيش والسلطات.',
        locationName: 'السالمية',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Zaatar+w+Zeit+Salmiya',
        imageUrl: '',
        tags: ['لبناني', 'سريع', 'صحي', 'مناقيش'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 191,
        name: 'Munch',
        category: 'مطعم فطور وعائلي',
        description: 'يقدم السلطات والسندويشات الصحية بخيار ممتاز لغداء خفيف.',
        locationName: 'مدينة الكويت',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Munch+Kuwait+City',
        imageUrl: '',
        tags: ['صحي', 'سلطات', 'سندويشات', 'غداء'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 192,
        name: 'Q at The Yard',
        category: 'مطعم فطور وعائلي',
        description: 'مطعم يقدم أطباق فطور وغداء عالمية في مجمع اليارد.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Q+at+The+Yard+Shuwaikh',
        imageUrl: '',
        tags: ['فطور', 'غداء', 'عالمي', 'مجمع'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 193,
        name: 'Roto',
        category: 'مطعم فطور وعائلي',
        description: 'متخصص في الدجاج المشوي (الروتيسري) وأطباق جانبية لذيذة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Roto+Shuwaikh',
        imageUrl: '',
        tags: ['دجاج', 'مشوي', 'روتيسري', 'لذيذ'],
        suitableFor: ['family', 'group'],
    },
    {
        id: 194,
        name: 'Prime & Toast',
        category: 'مطعم فطور وعائلي',
        description: 'وجهة فطور كلاسيكية تقدم أطباقاً متنوعة ومحبوبة.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Prime+and+Toast+Al+Bidaa',
        imageUrl: '',
        tags: ['فطور', 'كلاسيكي', 'متنوع', 'محبوب'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 195,
        name: 'Home Sweet',
        category: 'مطعم فطور وعائلي',
        description: 'يقدم الفطور والحلويات في أجواء منزلية.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Home+Sweet+Al+Bidaa',
        imageUrl: '',
        tags: ['فطور', 'حلويات', 'منزلي'],
        suitableFor: ['couple', 'family'],
    },
    {
        id: 196,
        name: 'Maison du croissant',
        category: 'مطعم فطور وعائلي',
        description: 'مخبز فرنسي متخصص في الكرواسان الطازج.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Maison+du+Croissant+Shuwaikh',
        imageUrl: '',
        tags: ['مخبز', 'فرنسي', 'كرواسان', 'طازج'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 197,
        name: 'The Kind Ones',
        category: 'مطعم فطور وعائلي',
        description: 'مطعم نباتي يقدم أطباقاً صحية ومبتكرة.',
        locationName: 'الشويخ',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Kind+Ones+Shuwaikh',
        imageUrl: '',
        tags: ['نباتي', 'صحي', 'مبتكر'],
        suitableFor: ['individual', 'couple'],
    },
    {
        id: 198,
        name: 'OVO',
        category: 'مطعم فطور وعائلي',
        description: 'يقدم قائمة كاملة تعتمد على البيض بشكل أساسي.',
        locationName: 'البدع',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=OVO+Restaurant+Al+Bidaa',
        imageUrl: '',
        tags: ['فطور', 'بيض', 'صباحي', 'صحي'],
        suitableFor: ['individual', 'couple', 'family'],
    },
    {
        id: 199,
        name: 'Cuts',
        category: 'مطعم فطور وعائلي',
        description: 'سلسلة مطاعم ستيك هاوس في مجمع المروج.',
        locationName: 'صباح السالم',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cuts+Steakhouse+Murouj',
        imageUrl: '',
        tags: ['ستيك', 'لحوم', 'عشاء', 'أمريكي', 'غداء'],
        suitableFor: ['couple', 'family', 'group'],
    },
    {
        id: 200,
        name: 'IHOP',
        category: 'مطعم فطور وعائلي',
        description: 'سلسلة عالمية متخصصة في البانكيك ووجبات الفطور الأمريكي.',
        locationName: 'الكوت مول',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=IHOP+Al+Kout+Mall',
        imageUrl: 'https://b.zmtcdn.com/data/pictures/5/18579225/32770281313670942e617d12f117a0a6.jpg',
        tags: ['فطور', 'بانكيك', 'أمريكي', 'عائلي', 'أطفال'],
        suitableFor: ['couple', 'family', 'group'],
    },
];